##########NetWorking###############
C_CONNECT=1
C_DISCONNECT=3
C_USER_ADD_CHAR=4
C_CHAR_ADD_MISSION=5
C_MISSION_UPDATE=6
C_CREATE_USER=2
C_CHAR_UPDATE=7
C_NEWPLAYER_INCOMING=8
C_USER_UPDATE=9
C_USER_OUTGOING=10
C_NPC_INCOMING=11
C_NPC_UPDATE=12
C_NPC_DESTROY=13
C_ADD_JUNK=14
C_NEW_MESSAGE_CHAT=15
C_ADD_EXPLOSION=16
C_BULLET_UPDATE=17
C_CHAR_INITIALVEL=19
C_NPC_INITIALVEL=20
C_DEATH_NEW_XML=21
C_CHAR_DESTROY=22
C_USER_DELETE_CHAR=23
C_JUNK_UPDATE=24
C_JUNK_REMOVE=25
##########ZONE###############
C_TYPEZONE_SPACE=1
C_TYPEZONE_STATION=2
##########NPC BEHAVIOR###############
C_BEHAVIOR_PATROL=1
C_BEHAVIOR_ATTACK=2
C_BEHAVIOR_DODGE=3
##########ITEM TYPE###############
C_ITEM_ENGINE=1
C_ITEM_WEAPON=2
C_ITEM_ENERGY=3
C_ITEM_CONTAINER=4
C_ITEM_ELECTRO=5
C_ITEM_RADAR=6
C_ITEM_MINERAL=11
C_ITEM_MINING=10
C_ITEM_SHIP=7
##########SLOT LOCATION###############
C_SLOT_FRONT=1
C_SLOT_REAR=2
C_SLOT_LEFT=3
C_SLOT_RIGHT=4
C_SLOT_MIDDLE=5
##########SKILL#######################
C_WEAPON_LASER_LIGHT=200
C_LIGHT_HUNTER=100
C_PILOTAGE=1
C_WEAPON=2


#############DIVERS##################
C_STEP_SIZE=1.0/60.0
C_SENDTICKS=1.0/4.0
#~ C_SENDTICKS=1.25
C_INTERACTION_ITEM=500
C_INTERACTION_ITEM_STATION=250

############DIALOGUE#################
C_DIALOG_TYPE_DIALOGUE=1
C_DIALOG_TYPE_RUMOR=2
C_DIALOG_TYPE_MISSION=3

############TYPE OBJECTIF##############
C_OBJECTIF_TRANSPORT=1
C_OBJECTIF_DESTROY=2

############STATUS MISSION############
C_STATEMISSION_DONTHAVE=0
C_STATEMISSION_INPROGRESS=1
C_STATEMISSION_FINISHED=2
C_STATEMISSION_SUCCESS=3

############TYPE REWARD####################
C_REWARD_COIN=1